/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.encriptador.vista;

import com.mycompany.encriptador.datos.GestorHistorial;
import com.mycompany.encriptador.logica.Encriptador;
import com.mycompany.encriptador.modelo.ConfiguracionManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Map;

/**
 *
 * @author Diego Calix
 */
  

    public class VistaEncriptador extends javax.swing.JFrame {
        private DefaultTableModel modeloTabla;
        private ConfiguracionManager configManager;

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEncriptador.class.getName());

        /**
         * Creates new form VistaEncriptador
         */
        public VistaEncriptador() {
            configManager = new ConfiguracionManager();
         
            initComponents();
            this.setLocationRelativeTo(null);
            configurarTabla();
            cargarDatosDesdeBD();
            asociarEventosLogicos();
        }

        private void configurarTabla() {
            modeloTabla = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            modeloTabla.addColumn("ID");
            modeloTabla.addColumn("Texto Original");
            modeloTabla.addColumn("Texto Encriptado");

            tablaHistorial.setModel(modeloTabla);
        }
        
        private void cargarDatosDesdeBD() {
    try {
        modeloTabla.setRowCount(0);

        java.util.List<Object[]> registros = GestorHistorial.obtenerHistorialCompleto();
        for (Object[] fila : registros) {
            modeloTabla.addRow(fila);
        }
       
        if (modeloTabla.getRowCount() > 0) {
            btnDesencriptar.setEnabled(true);
        }
    } catch (SQLException ex) {
        mostrarError("No se pudieron cargar los datos históricos: " + ex.getMessage());
    }
}

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEncriptar = new javax.swing.JButton();
        txtEntrada = new javax.swing.JTextField();
        btnDesencriptar = new javax.swing.JButton();
        btnCargarConfig = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        btnDesencriptar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encriptador");

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHistorial);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese la frase a encriptar:");

        btnEncriptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEncriptar.setText("Encriptar");

        txtEntrada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnDesencriptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDesencriptar.setText("Desencriptar");

        btnCargarConfig.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCargarConfig.setText("Cargar Configuración");

        BtnSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(this::BtnSalirActionPerformed);

        btnDesencriptar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDesencriptar1.setText("Eliminar seleccionado");
        btnDesencriptar1.addActionListener(this::btnDesencriptar1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnEncriptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesencriptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargarConfig)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesencriptar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnSalir)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(143, 143, 143))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDesencriptar)
                    .addComponent(btnEncriptar)
                    .addComponent(btnCargarConfig)
                    .addComponent(btnDesencriptar1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSalir)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(
            this, 
            "¿Estás seguro de que deseas salir?", 
            "Confirmar Salida", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
    );
    
    if (respuesta == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void btnDesencriptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesencriptar1ActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaHistorial.getSelectedRow();

    if (filaSeleccionada == -1) {
        mostrarError("Por favor, selecciona una fila de la tabla para eliminar.");
        return;
    }

    int idSeleccionado = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
    String textoOriginal = (String) modeloTabla.getValueAt(filaSeleccionada, 1);

    int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas eliminar este registro?\n\"" + textoOriginal + "\"",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            GestorHistorial.eliminarRegistro(idSeleccionado);

            modeloTabla.removeRow(filaSeleccionada);

            JOptionPane.showMessageDialog(this, 
                    "Registro eliminado correctamente de la base de datos.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);

            if (modeloTabla.getRowCount() == 0) {
                btnDesencriptar.setEnabled(false);
            }

        } catch (SQLException ex) {
            mostrarError("No se pudo eliminar el registro de la base de datos: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnDesencriptar1ActionPerformed

    private void asociarEventosLogicos() {

            btnCargarConfig.addActionListener(e -> {
                JFileChooser fileChooser = new JFileChooser(".");
                fileChooser.setDialogTitle("Seleccione el archivo config.txt");
                int seleccion = fileChooser.showOpenDialog(this);

                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    String ruta = fileChooser.getSelectedFile().getAbsolutePath();
                    try {
                        configManager.cargarDesdeArchivo(ruta);
                        JOptionPane.showMessageDialog(this,
                                "Configuración cargada correctamente.\nCaracteres mapeados: " + configManager.getMapaEncriptar().size(),
                                "Configuración Exitosa",
                                JOptionPane.INFORMATION_MESSAGE);

                        btnEncriptar.setEnabled(true);
                    } catch (IOException ex) {
                        mostrarError("No se pudo leer el archivo: " + ex.getMessage());
                    } catch (IllegalArgumentException ex) {
                        mostrarError("Formato de configuración inválido:\n" + ex.getMessage());
                    }
                }
            });

            btnEncriptar.addActionListener(e -> {
                String texto = txtEntrada.getText().trim();
                if (texto.isEmpty()) {
                    mostrarError("Por favor, escribe un texto antes de encriptar.");
                    return;
                }

                Map<Character, Character> mapaActual = configManager.getMapaEncriptar();
                String encriptado = Encriptador.encriptar(texto, mapaActual);

                try {
                    int idGuardado = GestorHistorial.guardarFraseYConfiguracion(texto, encriptado, mapaActual);

                    modeloTabla.addRow(new Object[]{idGuardado, texto, encriptado});
                    btnDesencriptar.setEnabled(true);
                    txtEntrada.setText(""); 

                } catch (SQLException ex) {
                    mostrarError("Error al guardar en la base de datos SQLite: " + ex.getMessage());
                }
            });

            btnDesencriptar.addActionListener(e -> {
                int filaSeleccionada = tablaHistorial.getSelectedRow();

                if (filaSeleccionada == -1) {
                    mostrarError("Por favor, selecciona una fila de la tabla para desencriptar.");
                    return;
                }

                int idSeleccionado = (int) modeloTabla.getValueAt(filaSeleccionada, 0);

                try {
                    String cifrado = GestorHistorial.obtenerTextoEncriptado(idSeleccionado);
                    if (cifrado == null) {
                        mostrarError("No se encontró el registro seleccionado en la base de datos.");
                        return;
                    }

                    Map<Character, Character> mapaInverso = GestorHistorial.obtenerMapaInversoPorFrase(idSeleccionado);

                    String desencriptado = Encriptador.desencriptar(cifrado, mapaInverso);

                    JOptionPane.showMessageDialog(this,
                            "--- Desencriptación Exitosa ---\n\n"
                            + "ID del registro: " + idSeleccionado + "\n"
                            + "Texto Cifrado: " + cifrado + "\n"
                            + "Texto Recuperado: " + desencriptado,
                            "Resultado Histórico",
                            JOptionPane.INFORMATION_MESSAGE);

                } catch (SQLException ex) {
                    mostrarError("Error de lectura en SQLite: " + ex.getMessage());
                }
            });
        }

        private void mostrarError(String mensaje) {
            JOptionPane.showMessageDialog(this, mensaje, "Error de Sistema", JOptionPane.ERROR_MESSAGE);
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new VistaEncriptador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton btnCargarConfig;
    private javax.swing.JButton btnDesencriptar;
    private javax.swing.JButton btnDesencriptar1;
    private javax.swing.JButton btnEncriptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTextField txtEntrada;
    // End of variables declaration//GEN-END:variables
}
