/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.encriptador.vista;

import com.mycompany.encriptador.datos.GestorHistorial;
import com.mycompany.encriptador.logica.Encriptador;
import com.mycompany.encriptador.modelo.ConfiguracionManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Map;

/**
 *
 * @author Diego Calix
 */
  

    public class VistaEncriptador extends javax.swing.JFrame {
        private DefaultTableModel modeloTabla;
        private ConfiguracionManager configManager;

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaEncriptador.class.getName());

        /**
         * Creates new form VistaEncriptador
         */
        public VistaEncriptador() {
            configManager = new ConfiguracionManager();
         
            // Inicializa componentes del Diseñador
            initComponents();
            this.setLocationRelativeTo(null);
            // Configuramos el JTable manualmente para que tenga sus columnas
            configurarTabla();
            cargarDatosDesdeBD();
            // Asociamos nuestra lógica
            asociarEventosLogicos();
        }

        private void configurarTabla() {
            modeloTabla = new DefaultTableModel() {
                // Hacemos que las celdas de la tabla no sean editables al hacer doble clic
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            // Agregamos las columnas requeridas
            modeloTabla.addColumn("ID");
            modeloTabla.addColumn("Texto Original");
            modeloTabla.addColumn("Texto Encriptado");

            tablaHistorial.setModel(modeloTabla);
        }
        
        private void cargarDatosDesdeBD() {
    try {
        // 1. Limpiamos cualquier fila que tenga la tabla por defecto para no duplicar
        modeloTabla.setRowCount(0);

        // 2. Llamamos a un método en el GestorHistorial para obtener los registros guardados
        java.util.List<Object[]> registros = GestorHistorial.obtenerHistorialCompleto();

        // 3. Recorremos los registros y los agregamos uno a uno a la tabla
        for (Object[] fila : registros) {
            modeloTabla.addRow(fila);
        }
        
        // Si la tabla tiene datos, habilitamos el botón de desencriptar por comodidad
        if (modeloTabla.getRowCount() > 0) {
            btnDesencriptar.setEnabled(true);
        }

    } catch (SQLException ex) {
        mostrarError("No se pudieron cargar los datos históricos: " + ex.getMessage());
    }
}

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEncriptar = new javax.swing.JButton();
        txtEntrada = new javax.swing.JTextField();
        btnDesencriptar = new javax.swing.JButton();
        btnCargarConfig = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHistorial);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese la frase a encriptar:");

        btnEncriptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEncriptar.setText("Encriptar");

        txtEntrada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btnDesencriptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDesencriptar.setText("Desencriptar");

        btnCargarConfig.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCargarConfig.setText("Cargar Configuración");

        BtnSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(this::BtnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEncriptar)
                .addGap(66, 66, 66)
                .addComponent(btnDesencriptar)
                .addGap(66, 66, 66)
                .addComponent(btnCargarConfig)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnSalir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDesencriptar)
                    .addComponent(btnEncriptar)
                    .addComponent(btnCargarConfig))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSalir)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(
            this, 
            "¿Estás seguro de que deseas salir?", 
            "Confirmar Salida", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
    );
    
    if (respuesta == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void asociarEventosLogicos() {

            // EVENTO 1: Cargar la configuración desde config.txt
            btnCargarConfig.addActionListener(e -> {
                JFileChooser fileChooser = new JFileChooser(".");
                fileChooser.setDialogTitle("Seleccione el archivo config.txt");
                int seleccion = fileChooser.showOpenDialog(this);

                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    String ruta = fileChooser.getSelectedFile().getAbsolutePath();
                    try {
                        configManager.cargarDesdeArchivo(ruta);
                        JOptionPane.showMessageDialog(this,
                                "Configuración cargada correctamente.\nCaracteres mapeados: " + configManager.getMapaEncriptar().size(),
                                "Configuración Exitosa",
                                JOptionPane.INFORMATION_MESSAGE);

                        btnEncriptar.setEnabled(true);
                    } catch (IOException ex) {
                        mostrarError("No se pudo leer el archivo: " + ex.getMessage());
                    } catch (IllegalArgumentException ex) {
                        mostrarError("Formato de configuración inválido:\n" + ex.getMessage());
                    }
                }
            });

            // EVENTO 2: Encriptar texto y guardarlo en la Base de Datos SQLite
            btnEncriptar.addActionListener(e -> {
                String texto = txtEntrada.getText().trim();
                if (texto.isEmpty()) {
                    mostrarError("Por favor, escribe un texto antes de encriptar.");
                    return;
                }

                Map<Character, Character> mapaActual = configManager.getMapaEncriptar();
                String encriptado = Encriptador.encriptar(texto, mapaActual);

                try {
                    // Guardamos en la base de datos y obtenemos el ID autogenerado
                    int idGuardado = GestorHistorial.guardarFraseYConfiguracion(texto, encriptado, mapaActual);

                    // Agregamos de manera visual la fila al JTable de forma inmediata
                    modeloTabla.addRow(new Object[]{idGuardado, texto, encriptado});

                    // Habilitamos el botón de desencriptar si hay al menos una fila
                    btnDesencriptar.setEnabled(true);
                    txtEntrada.setText(""); // Limpiamos la entrada

                } catch (SQLException ex) {
                    mostrarError("Error al guardar en la base de datos SQLite: " + ex.getMessage());
                }
            });

            // EVENTO 3: Desencriptar la fila que el usuario tenga seleccionada en la JTable
            btnDesencriptar.addActionListener(e -> {
                int filaSeleccionada = tablaHistorial.getSelectedRow();

                // Validación: Asegurarse de que el usuario haya hecho clic en una fila
                if (filaSeleccionada == -1) {
                    mostrarError("Por favor, selecciona una fila de la tabla para desencriptar.");
                    return;
                }

                // Obtenemos el ID de la fila seleccionada (Columna 0 de la tabla)
                int idSeleccionado = (int) modeloTabla.getValueAt(filaSeleccionada, 0);

                try {
                    // 1. Recuperamos el texto encriptado histórico de la BD
                    String cifrado = GestorHistorial.obtenerTextoEncriptado(idSeleccionado);
                    if (cifrado == null) {
                        mostrarError("No se encontró el registro seleccionado en la base de datos.");
                        return;
                    }

                    // 2. Recuperamos el mapa inverso exacto de esa frase
                    Map<Character, Character> mapaInverso = GestorHistorial.obtenerMapaInversoPorFrase(idSeleccionado);

                    // 3. Desencriptamos
                    String desencriptado = Encriptador.desencriptar(cifrado, mapaInverso);

                    // Mostramos el resultado de manera elegante en un cuadro de diálogo informativo
                    JOptionPane.showMessageDialog(this,
                            "--- Desencriptación Exitosa ---\n\n"
                            + "ID del registro: " + idSeleccionado + "\n"
                            + "Texto Cifrado: " + cifrado + "\n"
                            + "Texto Recuperado: " + desencriptado,
                            "Resultado Histórico",
                            JOptionPane.INFORMATION_MESSAGE);

                } catch (SQLException ex) {
                    mostrarError("Error de lectura en SQLite: " + ex.getMessage());
                }
            });
        }

        private void mostrarError(String mensaje) {
            JOptionPane.showMessageDialog(this, mensaje, "Error de Sistema", JOptionPane.ERROR_MESSAGE);
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaEncriptador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton btnCargarConfig;
    private javax.swing.JButton btnDesencriptar;
    private javax.swing.JButton btnEncriptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTextField txtEntrada;
    // End of variables declaration//GEN-END:variables
}
